#
# Copyright (C) 2026 The Team Win Recovery Project
#
# SPDX-License-Identifier: Apache-2.0
#

COMMON_PATH := device/amazon/mt8163-echo

include $(COMMON_PATH)/arch/$(DEVICE_ARCH).mk

# Traits
DEVICE_HAS_SCREEN ?= true
DEVICE_HAS_LEDS ?= false
DEVICE_USES_AB ?= false

# Kernel
BOARD_KERNEL_CMDLINE ?= bootopt=64S3,32N2,32N2
BOARD_KERNEL_BASE ?= 0x40000000
BOARD_KERNEL_OFFSET ?= 0
BOARD_KERNEL_PAGESIZE ?= 2048
BOARD_RAMDISK_OFFSET ?= 0x03400000
BOARD_MKBOOTIMG_ARGS ?= --base $(BOARD_KERNEL_BASE) --kernel_offset 0x00008000 --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --second_offset 0x00f00000 --tags_offset 0x08000000

DEVICE_KERNEL_IMAGE ?= Image.gz-dtb
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/$(DEVICE_KERNEL_IMAGE)

LZMA_RAMDISK_TARGETS ?= recovery

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE ?= 16777216

# Platform
TARGET_BOARD_PLATFORM := mt8163
TARGET_BOOTLOADER_BOARD_NAME := mt8163
TARGET_NO_BOOTLOADER := true

# Recovery
RECOVERY_VARIANT := twrp
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USE_CUSTOM_LUN_FILE_PATH ?= /sys/class/android_usb/android0/f_mass_storage/lun%.0d/file

# TWRP
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
TW_NO_HAPTICS := true

TW_INCLUDE_CRYPTO ?= true
ifeq ($(TW_INCLUDE_CRYPTO),true)
TW_CRYPTO_USE_SYSTEM_VOLD := true
endif

# Screen
ifeq ($(DEVICE_HAS_SCREEN),true)
TARGET_RECOVERY_PIXEL_FORMAT ?= "RGBX_8888"

TW_THEME ?= landscape_mdpi
TW_ROTATION ?= 90

RECOVERY_TOUCHSCREEN_SWAP_XY ?= true
RECOVERY_TOUCHSCREEN_FLIP_Y ?= true
else
TW_NO_SCREEN_UI := true
endif

# LEDs
ifeq ($(DEVICE_HAS_LEDS),true)
TW_STATUS_NOTIFY := true
TW_STATUS_HOOK := /sbin/led-status.sh
endif

# A/B
ifeq ($(DEVICE_USES_AB),true)
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS := boot system
PRODUCT_STATIC_BOOT_CONTROL_HAL := bootctrl_amzn
TARGET_RECOVERY_DEVICE_MODULES := update_engine_sideload

BOARD_BUILD_SYSTEM_ROOT_IMAGE := true

TW_INCLUDE_BCBTOOL := true
TW_DEFAULT_BACKUP_LIST ?= "/system_root;/data;/boot;"
TARGET_RECOVERY_DEVICE_DIRS ?= $(COMMON_PATH)/ab $(DEVICE_PATH)
else
TW_DEFAULT_BACKUP_LIST ?= "/system_image;/data;/boot;"
TARGET_RECOVERY_DEVICE_DIRS ?= $(COMMON_PATH) $(DEVICE_PATH)
endif

ALLOW_MISSING_DEPENDENCIES := true
